apiVersion: v1
kind: Service
metadata:
  name: dj-deploy
  labels:
    name: dj-deploy
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: dj-deploy
  type: NodePort
---
apiversion: apps/v1
kind: Deployment
metadata:
  name: dj-deploy
spec:
  selector:
    matchLabels:
      app: dj-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: dj-deploy
    spec:
      containers:
        - name: dj-deploy
          image: irisstal/training:djdocker
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
                valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: name
            - name: DB_USERNAME
                valueFrom:
                  configMapKeyRef:
                    name: db-credentials
                    key: username
            - name: DB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: db-credentials
                    key: password
